// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {Escrow} from "../src/Escrow.sol";

contract EscrowTest is Test {

    Escrow public escrow;

    address buyer = address(1);
    address seller = address(2);
    address arbitrator = address(3);

    uint256 amount = 1 ether;
    uint256 duration = 1 days;



    function setUp() public {
        escrow = new Escrow(buyer, seller, arbitrator, amount, duration);
    }



    function fundEscrow() internal {
        vm.deal(buyer, 10 ether);

        vm.prank(buyer);
        escrow.fundEscrow{value: amount}();
    }

    function moveToSubmittedState() internal {
        fundEscrow();

        vm.prank(seller);
        escrow.sellerAcceptWork();

        vm.prank(seller);
        escrow.submitWork();
    }

    function completeEscrow() internal {
        moveToSubmittedState();

        vm.prank(buyer);
        escrow.verifyWork();
    }



    function testDeployment() public {
        assertEq(escrow.buyer(), buyer);
        assertEq(escrow.seller(), seller);
        assertEq(escrow.arbitrator(), arbitrator);
        assertEq(escrow.amount(), amount);
        assertEq(uint256(escrow.state()), uint256(Escrow.State.CREATED));
    }



    function testBuyerCanFund() public {
        fundEscrow();
        assertEq(address(escrow).balance, amount);
    }

    function testNonBuyerCannotFund() public {
        vm.deal(seller, 10 ether);

        vm.prank(seller);
        vm.expectRevert(Escrow.OnlyBuyer.selector);
        escrow.fundEscrow{value: amount}();
    }

    function testCannotFundWrongAmount() public {
        vm.deal(buyer, 10 ether);

        vm.prank(buyer);
        vm.expectRevert(Escrow.InvalidAmount.selector);
        escrow.fundEscrow{value: 0.5 ether}();
    }

    function testCannotFundTwice() public {
        fundEscrow();

        vm.prank(buyer);
        vm.expectRevert(Escrow.InvalidState.selector);
        escrow.fundEscrow{value: amount}();
    }


    function testStateMovesToInProgress() public {
        fundEscrow();

        vm.prank(seller);
        escrow.sellerAcceptWork();

        assertEq(uint256(escrow.state()), uint256(Escrow.State.IN_PROGRESS));
    }

    function testCannotSubmitBeforeAccepting() public {
        fundEscrow();

        vm.prank(seller);
        vm.expectRevert(Escrow.InvalidState.selector);
        escrow.submitWork();
    }

    

    function testSellerWithdrawAfterCompletion() public {
        completeEscrow();

        uint256 sellerBalanceBefore = seller.balance;

        vm.prank(seller);
        escrow.withdrawFunds();

        assertEq(address(escrow).balance, 0);
        assertEq(seller.balance, sellerBalanceBefore + amount);
        assertTrue(escrow.fundsWithdrawn());
    }

    function testCannotWithdrawTwice() public {
        completeEscrow();

        vm.prank(seller);
        escrow.withdrawFunds();

        vm.prank(seller);
        vm.expectRevert(Escrow.InvalidState.selector);
        escrow.withdrawFunds();
    }

  
    function testOnlyArbitratorCanResolve() public {
        moveToSubmittedState();

        vm.prank(buyer);
        escrow.raiseDispute();

        vm.prank(buyer);
        vm.expectRevert(Escrow.OnlyArbitrator.selector);
        escrow.resolveDispute(true);
    }

    function testArbitratorResolvesDispute() public {
        moveToSubmittedState();

        vm.prank(buyer);
        escrow.raiseDispute();

        vm.prank(arbitrator);
        escrow.resolveDispute(true);

        assertEq(uint256(escrow.state()), uint256(Escrow.State.RESOLVED));
    }

    function testLoserCannotWithdrawAfterDispute() public {
        moveToSubmittedState();

        vm.prank(buyer);
        escrow.raiseDispute();

        vm.prank(arbitrator);
        escrow.resolveDispute(true); // buyer wins

        vm.prank(seller);
        vm.expectRevert(Escrow.InvalidState.selector);
        escrow.withdrawFunds();
    }


    // Fuzz tests have parameters. They are automatically generated by the testing framework (forge) and can be used to test a wide range of inputs, including edge cases that we might not have thought of. In this case, we are fuzzing the funding function with different values to ensure that it correctly reverts when an incorrect amount is sent.
    function testFuzzFunding(uint96 value) public {
        vm.assume(value != amount); // vm.assume is used to filter out values that we don't want to test with. In this case, we want to test with values that are not equal to the required amount, to ensure that the contract correctly reverts when an incorrect amount is sent.
        vm.assume(value > 0);

        vm.deal(buyer, value);

        vm.prank(buyer);
        vm.expectRevert();
        escrow.fundEscrow{value: value}();
    }

    function testFuzzOnlyBuyerCanFund(address attacker, uint96 value) public {

        vm.assume(attacker != buyer);
        vm.assume(attacker != address(0));

        vm.deal(attacker, value);

        vm.prank(attacker);
        vm.expectRevert(Escrow.OnlyBuyer.selector);

        escrow.fundEscrow{value: value}();
    }

}
