// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {EscrowFactory} from "../src/EscrowFactory.sol";
import {Escrow} from "../src/Escrow.sol";

contract EscrowFactoryTest is Test {

    EscrowFactory factory;

    address buyer = address(1);
    address seller = address(2);
    address arbitrator = address(3);

    uint256 amount = 1 ether;
    uint256 duration = 1 days;


    function setUp() public {
        factory = new EscrowFactory(arbitrator);
    }

 

    function testCreateEscrow() public {

        address escrowAddress = factory.createEscrow(
            buyer,
            seller,
            amount,
            duration
        );

        assertNotEq(escrowAddress, address(0));

        Escrow escrow = Escrow(payable(escrowAddress));

        assertEq(escrow.buyer(), buyer);
        assertEq(escrow.seller(), seller);
        assertEq(escrow.arbitrator(), arbitrator);
        assertEq(escrow.amount(), amount);
    }

   

    function testEscrowStoredInArray() public {

        address escrowAddress = factory.createEscrow(
            buyer,
            seller,
            amount,
            duration
        );

        address stored = address(factory.escrows(0));

        assertEq(stored, escrowAddress);
    }

    function testEscrowCountIncreases() public {

        uint256 beforeCount = factory.escrowsLength();

        factory.createEscrow(
            buyer,
            seller,
            amount,
            duration
        );

        uint256 afterCount = factory.escrowsLength();

        assertEq(afterCount, beforeCount + 1);
    }

    function testMultipleEscrowsStored() public {

        factory.createEscrow(buyer, seller, amount, duration);
        factory.createEscrow(buyer, seller, amount, duration);

        assertEq(factory.escrowsLength(), 2);
    }

    

    function testCannotCreateWithZeroBuyer() public {

        vm.expectRevert();

        factory.createEscrow(
            address(0),
            seller,
            amount,
            duration
        );
    }

    function testCannotCreateWithZeroSeller() public {

        vm.expectRevert();

        factory.createEscrow(
            buyer,
            address(0),
            amount,
            duration
        );
    }

    function testBuyerCannotEqualSeller() public {

        vm.expectRevert();

        factory.createEscrow(
            buyer,
            buyer,
            amount,
            duration
        );
    }

    function testCannotCreateWithZeroAmount() public {

        vm.expectRevert();

        factory.createEscrow(
            buyer,
            seller,
            0,
            duration
        );
    }

    

    function testEmitsEventOnEscrowCreation() public {

        vm.expectEmit(true, true, false, false);


        // emits are generated by the contract itself not the instance, so factory.createEscrow will not work.
        emit EscrowFactory.EscrowCreated(
            buyer,
            seller,
            amount,
            block.timestamp + duration,
            address(0) // ignored
        );

        factory.createEscrow(
            buyer,
            seller,
            amount,
            duration
        );
    }
}
